---

# Usage: policy_name is one of a set that would be managed by the role. 
# - { role: ansible-iam-role, iam_role_name: 'delme', policy_name: 'account_secrets' }


# can't have a dynamic file name in the lookup. The solution is template files on remote
# - name: attach policy
#   iam_policy: >
#     iam_type=role
#     iam_name="{{iam_role_name}}"
#     policy_name="{{policy_name}}"
#     policy_json="{{lookup( 'template', {{policy.json.j2}} ) }}"
#     state=present

- name: template
  template:
    src: "{{policy_name}}.json.j2"
    dest: "/tmp/{{policy_name}}.json"

- name:
  iam:
    iam_type: role
    name: "{{iam_role_name}}"
    state: present

- name: attach policy
  iam_policy:
    iam_type: role
    iam_name: "{{iam_role_name}}"
    policy_name: "{{policy_name}}"
    policy_document: "/tmp/{{policy_name}}.json"
    state: present

# Cleanup template file?